apiVersion: v1
kind: Service
metadata:
  name: k8s-envoy
  labels:
    app: k8s-envoy
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: k8s-envoy